# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Run Cypress e2e on push

on:
  push:
    branches:
      - 'master'
      
jobs:
  cypress-test:
    name: cypress e2e,
    runs-on: windows-2022
    container: node14.19.0-chrome100-ff99-edge
    steps:
      - uses: actions/checkout@v2.4.2
      
      - name: install cypress and verify
        run: |
          npm ci
          $(npm bin)/cypress verify
          
      - name: Run Cypress e2e tests
        run: npm run cypress:e2e
        continue-on-error: false
